### ISSUE TITLE
[quote] paragraph style renders poorly

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-georeferencing-best-practices#46] opened 2020-12-29 01:47 UTC
There is a giant starting quote and large font with large line separation. It looks nothing like the example under Section 15.3 on  quote and verse paragraph styles in https://asciidoc.org/userguide.html. The happens in Section 1.6 in the FGDC quote and in the Section 2.7 Murphey quote. 

I have no idea how to fix this. I tried removing the NOTE ---- ---- to see if that would help, but it didn't.   Help @MattBlissett or @kcopas.

**Comment by ArthurChapman** [comment] 2020-12-29 03:46
Cf with one under 2.7 also

**Comment by kcopas** [comment] 2020-12-30 13:14
Okay, so the style shows as written: see [this example](https://docs.gbif.org/sensitive-species-best-practices/master/en/#determining-sensitivity) from the sensitive species guide.

It doesn't wow me, tbh, but it's a feature, not a bug at this point, and I don't think we should let that stand in the way of publishing the releases. The documents will pick up any CSS changes we choose to make later without any change of the content, so I'm closing and proceeding with the first-final releases.

**Closed as completed by kcopas** 2020-12-30 13:14 UTC

**Comment by MattBlissett** [comment] 2021-01-05 15:29
PS -- we use AsciiDoctor, not AsciiDoc. The latter is an older, less-flexible system, although it is very similar.

The AsciiDoctor manual: https://asciidoctor.org/docs/user-manual/#quote §35.1 looks similar to what we have, although as Kyle says, it's all a matter of CSS styling.

**Comment by tucotuco** [comment] 2021-01-05 17:14
It looks like it should be possible to link to custom css.

https://asciidoctor.org/docs/user-manual/#styling-the-html-with-css
https://asciidoctor.org/docs/user-manual/#applying-a-theme

Can we do that?
